### ISSUE TITLE
Warning in Home Assistant: IntesisHome Integration May Stop Working (Request for Maintenance)

### ISSUE THREAD

**Issue by kitopopo** [jnimmo/hass-intesishome#20]
Hi @jnimmo ,

First of all, I want to thank you for creating the intesishome integration, which has been invaluable for controlling air conditioners within Home Assistant.

However, I’ve recently encountered a warning in Home Assistant that suggests the integration might stop functioning in future releases (specifically starting with version 2025.1). The warning is as follows:

**2024-12-10 16:20:43.058 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration intesishome with title: intesishome_local IS-IR-WIFI-1 (DEVICE_xxxxxxxx) and entry_id: xxxxxx, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1, please report this issue.**

I know you mentioned that you no longer own Intesis devices and don't have the time to continue maintaining the project. However, I would like to know if you might consider resuming the maintenance, as this integration is critical for many users like myself. Additionally, a local implementation of the integration would be a great help, as it currently relies on the cloud.

If resuming the maintenance is not feasible for you, I would appreciate it if you could point me in the direction of anyone else who may be interested in taking over the project. Alternatively, if there’s a way to implement this integration locally, that would be very helpful.

I understand this project has been a personal effort for you, and I would love to support you in some way. If you decide to resume the maintenance of the integration, I will happily invite you to a coffee as a thank you for your effort. I’ve seen that you’ve spent many mornings at the coffee shop working on this project, so I’d love to return some of that energy with a coffee on me!

If time is a limiting factor, I am also willing to collaborate or support in any way I can. Any contribution you can make would be greatly appreciated in keeping this valuable tool functional.

Thank you in advance for considering my request, and I look forward to hearing from you.

Best regards,

**Comment by nerijus** [comment]
It's probably best to fork this repo. @autumnwalker , @srkoster , could you please consider it?

**Comment by autumnwalker** [comment]
I'd love for someone to fork it that knows how to maintain it. I'm not a developer. I submit a PR to fix this issue because I fumbled my way through the fix in my local code (and it still works in my local code btw), but I wouldn't know how to troubleshoot and fix issues, etc. on any sort of scale.

**Comment by kitopopo** [comment]
What bad luck I have, no one is going to continue this amazing integration. Perhaps @srkoster is a developer? Could anyone else help? Hello! @jnimmo , have you considered having several coffees? Since you don’t have Intesis Home modules anymore, I can start testing your integration if you have a bit of time to take it up again. Sorry for the inconvenience. Thanks again!

**Comment by kitopopo** [comment]
Hello @autumnwalker and @srkoster,

I wanted to thank you both for the contributions made to the IntesisHome integration, especially for the fixes in PRs #16, #18, and #19. I saw that a new version was released on December 14th, and although I haven't had the chance to fully test it yet, I truly appreciate the work you've done to address the issues with the deprecated async_forward_entry_setup and to improve performance with device handling.

Additionally, I want to thank you for the effort you put into uploading the new version to @jnimmo . It’s great to see the integration being actively maintained.

Thank you for your continued effort in keeping the integration compatible with future versions of Home Assistant. Your work is greatly appreciated!

Best regards,

**Comment by autumnwalker** [comment]
@kitopopo the error you described should be resolved in 3fa2040ce7d1a5e5b5769f14e81ee8dcc01dd774. Can you please confirm / close? 

The maintainer thing is still valid, but shout out to @jnimmo for pulling the changes and releasing the update!

**Comment by kitopopo** [comment]
> @kitopopo the error you described should be resolved in 3fa2040ce7d1a5e5b5769f14e81ee8dcc01dd774. Can you please confirm / close? 
> 
> The maintainer thing is still valid, but shout out to @jnimmo for pulling the changes and releasing the update!

Hi,

Thank you for your work on this integration. In the latest version (1.0.9), the original issue has been resolved, but I’ve noticed two additional problems:

1. Version in manifest.json file: The version number hasn’t been updated to 1.0.9, so Home Assistant still shows version 1.0.6 within the integration. This can cause confusion when verifying if the latest version is in use.


2. New error: After updating to version 1.0.9, the following error appears:

Entity None (<class 'custom_components.intesishome.climate.IntesisAC'>) implements HVACMode(s): heat_cool, heat, dry, fan_only, cool, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please report it to the author of the 'intesishome' custom integration

As a temporary fix, I’ve added the following lines to the __init__ method of the IntesisAC class to prevent the error:

Inside the init method of the IntesisAC class

self._attr_supported_features |= ClimateEntityFeature.TURN_ON
self._attr_supported_features |= ClimateEntityFeature.TURN_OFF

With this change, the error disappears entirely, but I’m not sure if this is the correct solution.

Thank you very much for your collaboration in addressing these issues.

Best regards, and thanks again for your efforts @jnimmo @autumnwalker

**Comment by srkoster** [comment]
Hi @kitopopo ,

I've already drafted a PR #22 to implement turn_on/turn_off
